# Generated by Django 3.2.8 on 2022-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Choose...'), ('Technology', 'Technology'), ('Software', 'Software'), ('Business', 'Business'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food')], default='category', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.URLField(),
        ),
    ]
